language: java
jdk:
- oraclejdk8
install: true
script:
- "./gradlew clean"
- "./gradlew setupCIWorkspace"
- "./gradlew build"
deploy:
  provider: bintray
  file: "/bintray/descriptor.json"
  user: p3pp3rf1y
  key:
    secure: MX19f7iLjdSyDDpbiUIGL6Wwa2exDqTm31Cc2c8JqEG42mp7THotISzheMAYpCt9ogyordwRAkkfHhdOPDSF1sUxv0qrCrbO2bkCvC6kDJenoAyUl+WVfLMHBF1ibowQOoO3waPk/AuKrVVXvVcckgZDdHcR/k0JVKHbaBfjYsldXn9P1jF6btmyhCE2H/0x4pjYTYdo0Ds41IiqNVga0Dwjoyx6Qb439v00GeYn6b4qI/3/CsgnvSCxOjppyLmBXGOl/81UpYLI3Wel5lI1pSJ/IipviG9JgeumgHYKyxg7S01KSvRRUJcmRgGO0efQiZrs8Oxj6Ew9SVpBV844QClS0/FDgvyUnz1qLBlPVVXKFl3kAKbEWI3fAfHDRAgQCRputissvsOc9F9SPvD7zYChC9VQJ7H7wgNeG9WYPhWjAYJX48k3785rdT5vpWJ785tTKiGossptWcI7X9lp0k7WJbyt1O8mloRVCRHnf17p9yiy2Ni7bqHQkeHNdiLMjdk2OpBf279astcysii03Y40AS//CSTKLrdNNI4ZGpFcx5hkiJ2zMzl2/JZyozSlgtlNRGQGpQKVbxxtR1F+quLNGqAn09sGcuOdNK3jiUckWfuucwklfYtp0vIuibM4IwIu85UCulfMi6oODbbgk1R1x4zL4WAq9z9EAtyixNc=
  on:
    all_branches: true